import { useCallback, useEffect, useRef, useState } from "react";
import type { JSONContent } from "@tiptap/core";
import Icon from "../components/Icon";
import SharedEditor, { BubbleIcon, type ParagraphTarget } from "./SharedEditor";
import { api, ApiError, roleName, uuid, type Member, type Message, type Profile, type Role, type SharedDocData, type SharedDocInfo, type Thread, type Workspace } from "./api";
import { LiveDocument } from "./live";
import { localOrigin } from "./replica";
import { Auth } from "./Auth";
import { Logo, UserAvatar, Field, Modal, ExitIcon } from "./ui";
import "./shared.css";

const displayTitle = (title: string) => title.trim() || "无标题";
export default function SharedApp() {
  const [profile, setProfile] = useState<Profile | null>(null); const [checking, setChecking] = useState(true); const [error, setError] = useState("");
  useEffect(() => { document.title = "WriteME · 一起把工作写好"; void api<Profile>("me").then(setProfile).catch(error => { if (!(error instanceof ApiError && error.status === 401)) setError("暂时连接不上服务器，请检查网络后重试"); }).finally(() => setChecking(false)); }, []);
  if (checking) return <div className="shared-app shared-loading"><Logo /><span>正在打开你的工作区…</span></div>;
  if (!profile || profile.needsSetup) return <Auth profile={profile} onLogin={setProfile} initialError={error} />;
  return <WorkspaceApp profile={profile} logout={async () => { await api("logout", "POST"); setProfile(null); }} />;
}
function WorkspaceApp({ profile, logout }: { profile: Profile; logout: () => Promise<void> }) {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [documents, setDocuments] = useState<SharedDocInfo[]>([]);
  const [active, setActive] = useState<string | null>(null); const [live, setLive] = useState<LiveDocument | null>(null); const [revision, setRevision] = useState(0); const [query, setQuery] = useState("");
  const [error, setError] = useState(""); const [modal, setModal] = useState<"workspace" | "members" | "delete" | "recover" | null>(null); const [loadVersion, setLoadVersion] = useState(0);
  const [trash, setTrash] = useState(false); const [comments, setComments] = useState(false); const [paragraph, setParagraph] = useState<ParagraphTarget | null>(null); const [sidebar, setSidebar] = useState(() => innerWidth > 900); const [loading, setLoading] = useState(false);
  const closeModal = useCallback(() => setModal(null), []);
  const run = useCallback(async (action: () => Promise<void>) => { try { setError(""); await action(); } catch (error) { setError(error instanceof Error ? error.message : "暂时无法完成操作"); } }, []);
  useEffect(() => { void run(async () => { const all = await api<Workspace[]>("workspaces"); setWorkspaces(all); setWorkspace(all.find(item => item.id === localStorage.getItem("writeme-last-workspace")) ?? all[0] ?? null); }); }, [run]);
  useEffect(() => {
    if (!workspace) return; let gone = false; localStorage.setItem("writeme-last-workspace", workspace.id);
    const refresh = async () => { try { const docs = await api<SharedDocInfo[]>(`workspaces/${workspace.id}/documents${trash ? "?trash=true" : ""}`); if (!gone) setDocuments(docs); } catch { /* Connection status in the active editor retains unsaved work. */ } };
    void refresh(); const timer = setInterval(() => void refresh(), 6000); return () => { gone = true; clearInterval(timer); };
  }, [workspace, trash]);
  useEffect(() => {
    let closed = false; let current: LiveDocument | undefined; let unsubscribe: (() => void) | undefined; setLive(null); setComments(false); setParagraph(null);
    if (!active) return; setLoading(true);
    void run(async () => { const data = await api<SharedDocData>(`shared/${active}`); if (closed) return; current = new LiveDocument(data, profile.id); unsubscribe = current.subscribe(() => setRevision(value => value + 1)); setLive(current); }).finally(() => { if (!closed) setLoading(false); });
    return () => { closed = true; unsubscribe?.(); current?.dispose(); };
  }, [active, profile.id, run, loadVersion]);
  const selectWorkspace = (selected: Workspace) => { setWorkspace(selected); setActive(null); setTrash(false); setDocuments([]); if (innerWidth <= 900) setSidebar(false); };
  const createDocument = () => run(async () => { if (!workspace) return; const data = await api<SharedDocData>(`workspaces/${workspace.id}/documents`, "POST", { title: "" }); setDocuments(items => [data.document, ...items]); setActive(data.document.id); setTrash(false); });
  const title = live?.replica.title.toString() ?? "";
  const count = live?.replica.readThreads().reduce((sum, thread) => sum + thread.messages.filter(message => !message.deleted).length, 0) ?? 0;
  const commentOn = useCallback((target: ParagraphTarget | null) => { setParagraph(target); setComments(true); }, []);
  const peers = [...new Map((live?.peers ?? []).map(peer => [peer.accountId, peer])).values()];
  const shown = documents.filter(document => displayTitle(document.title).toLowerCase().includes(query.toLowerCase()));
  return <div className={`shared-app shared-shell${sidebar ? " sidebar-open" : " sidebar-closed"}`} data-revision={revision}>
    <header className="shared-topbar"><Logo small /><button className="shared-icon" aria-label="显示工作区导航" onClick={() => setSidebar(!sidebar)}><Icon name="panel" /></button><div className="shared-breadcrumb">{active ? displayTitle(title) : trash ? "回收站" : workspace?.name ?? "我的工作台"}</div><div className="shared-top-actions">{workspace && <button className="shared-button shared-share" onClick={() => setModal("members")}><PeopleIcon />共享</button>}{live && <><div className="shared-peers" aria-label={`${peers.length} 人在线`}>{peers.map(peer => <span key={peer.accountId} title={`${peer.displayName} · 在线`}><UserAvatar name={peer.displayName} color={peer.color} /></span>)}</div><button className={`shared-button ${comments ? "selected" : ""}`} onClick={() => { setParagraph(null); setComments(!comments); }}><BubbleIcon />评论{count > 0 && <span className="shared-badge">{count}</span>}</button><button className="shared-icon" aria-label="撤销" title="撤销" disabled={!live.canWrite || !live.replica.undo.canUndo()} onClick={() => live.replica.undo.undo()}>↶</button><button className="shared-icon" aria-label="重做" title="重做" disabled={!live.canWrite || !live.replica.undo.canRedo()} onClick={() => live.replica.undo.redo()}>↷</button><button className="shared-icon" aria-label="删除当前文档" title="移至回收站" disabled={!live.canWrite} onClick={() => setModal("delete")}><Icon name="trash" size={17} /></button></>}</div></header>
    <aside className="shared-sidebar"><div className="shared-space-picker"><span className="shared-space-square">{[...(workspace?.name ?? "工作")][0]}</span><select aria-label="切换共享工作区" value={workspace?.id ?? ""} onChange={event => { const item = workspaces.find(item => item.id === event.target.value); if (item) selectWorkspace(item); }}><option value="" disabled>共享工作区</option>{workspaces.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="shared-icon" aria-label="创建工作区" title="创建工作区" onClick={() => setModal("workspace")}><Icon name="plus" size={16} /></button></div>
      <div className="shared-search"><Icon name="search" size={16} /><input aria-label="搜索共享文档" placeholder="搜索文档" value={query} onChange={event => setQuery(event.target.value)} /><kbd>⌕</kbd></div>
      <button className={`shared-nav ${!trash && !active ? "active" : ""}`} onClick={() => { setTrash(false); setActive(null); }}><Icon name="file" size={17} />所有文档<span>{trash ? "" : documents.length}</span></button>
      {workspace && <button className="shared-nav" onClick={() => setModal("members")}><PeopleIcon />工作区成员</button>}
      <div className="shared-list-label"><span>{trash ? "回收站" : "工作区文档"}</span>{workspace?.role !== "viewer" && workspace && !trash && <button className="shared-icon" aria-label="新建文档" title="新建文档" onClick={() => void createDocument()}><Icon name="plus" size={16} /></button>}</div>
      <div className="shared-document-list">{shown.map(document => <div key={document.id} className={`shared-document-item ${active === document.id ? "selected" : ""}`}><button onClick={() => { if (trash) return; setActive(document.id); if (innerWidth <= 900) setSidebar(false); }} disabled={trash}><Icon name="file" size={16} /><span>{displayTitle(live?.data.document.id === document.id ? title : document.title)}</span></button>{trash && workspace?.role !== "viewer" && <button className="shared-restore" onClick={() => void run(async () => { await api(`shared/${document.id}/restore`, "POST"); setDocuments(items => items.filter(item => item.id !== document.id)); })}>恢复</button>}</div>)}
      {!shown.length && <div className="shared-list-empty">{query ? "没有匹配的文档" : trash ? "回收站是空的" : "从第一篇文档开始"}</div>}</div>
      <div className="shared-sidebar-bottom"><button className={`shared-nav ${trash ? "active" : ""}`} onClick={() => { setActive(null); setTrash(!trash); }}><Icon name="trash" size={16} />回收站</button>
      <div className="shared-current-user"><UserAvatar name={profile.displayName} /><div><b>{profile.displayName}</b><small>@{profile.publicId}</small></div><button className="shared-icon" title="退出登录" aria-label="退出登录" onClick={() => void run(logout)}><ExitIcon /></button></div></div>
    </aside><div className="shared-main">
      {error && <div className="shared-banner" role="alert"><span>{error}</span><button onClick={() => setError("")} aria-label="关闭提示"><Icon name="close" size={15} /></button></div>}
      {live ? <div className="shared-document-layout"><main className="shared-paper-scroll"><article className="shared-paper"><input className="shared-document-title" aria-label="共享文档标题" placeholder="无标题" maxLength={500} value={title} readOnly={!live.canWrite} onChange={event => live.replica.setTitle(event.target.value)} onCompositionStart={() => live.setComposing(true)} onCompositionEnd={() => setTimeout(() => live.setComposing(false), 0)} />
      {live.error && <div className="shared-error" role="alert">{live.error}<button className="shared-link" onClick={() => downloadDraft(live)}>导出本地草稿</button><button className="shared-link" onClick={() => setModal("recover")}>重新打开服务器版本</button></div>}
      <SharedEditor live={live} onComment={commentOn} /><div className="shared-paper-footer"><div className="shared-document-meta"><span className={`shared-connection-dot ${live.status.startsWith("所有") || live.status.startsWith("已连接") ? "online" : ""}`} /><span role="status">{live.status}</span>{live.role === "viewer" && <span className="shared-access-label">仅阅读</span>}</div><button onClick={() => commentOn(null)}><BubbleIcon />添加文档评论</button></div></article></main>{comments && <Comments live={live} profile={profile} target={paragraph} close={() => setComments(false)} all={() => setParagraph(null)} />}</div>
      : <main className="shared-home"><div className="shared-home-intro"><span className="shared-eyebrow">{workspace?.name ?? "我的工作台"}</span><h1>{trash ? "回收站" : workspace ? "所有文档" : `你好，${profile.displayName}`}</h1><p>{workspace ? "你的文档，以及正在一起完成的工作。" : "创建一个工作区，或请伙伴用你的个人 ID 添加你。"}</p><button className="shared-primary" onClick={() => workspace ? void createDocument() : setModal("workspace")} disabled={workspace?.role === "viewer" || loading}><Icon name="plus" size={18} />{workspace ? "新建文档" : "创建工作区"}</button></div>{loading ? <p className="shared-muted">正在打开文档…</p> : workspace && !trash ? <div className="shared-document-cards">{shown.map(doc => <button key={doc.id} onClick={() => setActive(doc.id)}><Icon name="file" size={23} /><h3>{displayTitle(doc.title)}</h3><span>{new Date(doc.updatedAt).toLocaleDateString("zh-CN", { month: "long", day: "numeric" })}更新</span></button>)}</div> : !workspace && <div className="shared-id-card"><UserAvatar name={profile.displayName} /><div><b>{profile.displayName}</b><span>@{profile.publicId}</span></div><small>把这个 ID 告诉你的伙伴</small></div>}</main>}
    </div>
    {modal === "workspace" && <Modal title="创建工作区" description="用项目、团队或一件正在做的事来命名。" close={closeModal}><form onSubmit={event => { event.preventDefault(); const name = new FormData(event.currentTarget).get("name"); void run(async () => { const created = await api<Workspace>("workspaces", "POST", { name }); setWorkspaces(items => [...items, created]); selectWorkspace(created); closeModal(); }); }}><Field label="工作区名称"><input name="name" placeholder="例如：产品设计小组" maxLength={80} required /></Field><button className="shared-primary" type="submit">创建工作区 →</button></form>{error && <p className="shared-error">{error}</p>}</Modal>}
    {modal === "members" && workspace && <Members workspace={workspace} close={closeModal} />}
    {modal === "recover" && live && <Modal title="重新打开服务器版本？" description="先下载当前草稿和评论作为副本，再读取服务器内容。浏览器中原有的草稿也会保留。" close={closeModal}><div className="shared-modal-actions"><button className="shared-button" onClick={closeModal}>取消</button><button className="shared-primary" onClick={() => { downloadDraft(live); void run(async () => { await api<SharedDocData>(`shared/${live.data.document.id}`); live.useFreshCache(); closeModal(); setLoadVersion(value => value + 1); }); }}>保留草稿并重新打开</button></div>{error && <p className="shared-error" role="alert">{error}</p>}</Modal>}
    {modal === "delete" && live && <Modal title="将文档移至回收站？" description={`「${displayTitle(title)}」会从所有成员的文档列表移除，你可以在回收站恢复。`} close={closeModal}><div className="shared-modal-actions"><button className="shared-button" onClick={closeModal}>取消</button><button className="shared-danger" onClick={() => void run(async () => { await api(`shared/${active}`, "DELETE"); setDocuments(items => items.filter(item => item.id !== active)); setActive(null); closeModal(); })}>移至回收站</button></div></Modal>}
  </div>;
}
function Members({ workspace, close }: { workspace: Workspace; close: () => void }) {
  const [members, setMembers] = useState<Member[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(() => api<Member[]>(`workspaces/${workspace.id}/members`).then(setMembers), [workspace.id]);
  useEffect(() => { void refresh().catch(error => setError(error.message)); }, [refresh]);
  const change = async (action: () => Promise<unknown>) => { setBusy(true); setError(""); try { await action(); await refresh(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } };
  return <Modal title="工作区成员" description={`${workspace.name} · ${members.length} 位成员`} close={close}>{workspace.role === "owner" && <form className="shared-invite" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void change(async () => { await api(`workspaces/${workspace.id}/members`, "PUT", { publicId: data.get("id"), role: data.get("role") }); form.reset(); }); }}><Field label="通过个人 ID 添加成员"><input name="id" placeholder="@ 对方的个人 ID" required maxLength={33} /></Field><div className="shared-form-row"><select name="role" aria-label="新成员权限"><option value="editor">可编辑和评论</option><option value="viewer">仅阅读</option><option value="owner">所有者</option></select><button className="shared-primary" disabled={busy}>添加成员</button></div></form>}
    <div className="shared-members">{members.map(member => <div key={member.accountId} className="shared-member"><UserAvatar name={member.displayName} /><div><b>{member.displayName}</b><small>@{member.publicId}</small></div>{workspace.role === "owner" ? <><select aria-label={`${member.displayName}的权限`} disabled={busy} value={member.role} onChange={event => void change(() => api(`workspaces/${workspace.id}/members`, "PUT", { publicId: member.publicId, role: event.target.value }))}>{(["owner", "editor", "viewer"] as Role[]).map(role => <option key={role} value={role}>{roleName(role)}</option>)}</select><button className="shared-icon" title="移除成员" aria-label={`移除${member.displayName}`} disabled={busy} onClick={() => void change(() => api(`workspaces/${workspace.id}/members/${member.accountId}`, "DELETE"))}><Icon name="close" size={15} /></button></> : <small>{roleName(member.role)}</small>}</div>)}</div>{error && <p className="shared-error" role="alert">{error}</p>}</Modal>;
}
function findNode(root: JSONContent, id: string): JSONContent | null { if (root.attrs?.writemeId === id) return root; for (const child of root.content ?? []) { const found = findNode(child, id); if (found) return found; } return null; }
function Comments({ live, profile, target, close, all }: { live: LiveDocument; profile: Profile; target: ParagraphTarget | null; close: () => void; all: () => void }) {
  const [text, setText] = useState(() => live.commentDrafts.get(`${live.data.document.id}:${target?.id ?? "document"}`) ?? ""); const [reply, setReply] = useState<{ threadId: string; message: Message } | null>(null); const [editing, setEditing] = useState<{ threadId: string; message: Message } | null>(null); const [error, setError] = useState(""); const [confirm, setConfirm] = useState<{ thread: Thread; message: Message } | null>(null);
  const input = useRef<HTMLTextAreaElement>(null); const drafts = useRef(live.commentDrafts); const key = `${live.data.document.id}:${editing ? `edit:${editing.message.id}` : reply ? `reply:${reply.message.id}` : target?.id ?? "document"}`; const draftKey = useRef(key);
  useEffect(() => () => { drafts.current.set(draftKey.current, text); }, [text]);
  useEffect(() => { if (draftKey.current !== key) { drafts.current.set(draftKey.current, text); setText(drafts.current.get(key) ?? editing?.message.text ?? ""); draftKey.current = key; } }, [key, editing, text]);
  useEffect(() => { setReply(null); setEditing(null); setConfirm(null); }, [target?.id]);
  const root = live.replica.readRoot(); const node = target ? findNode(root, target.id) : null; const allThreads = live.replica.readThreads();
  const threads = target ? allThreads.filter(thread => ((node?.attrs?.writemeCommentIds ?? []) as string[]).includes(thread.id) || node?.content?.some(run => run.marks?.some(mark => mark.type === "comment" && (mark.attrs?.ids as string[])?.includes(thread.id)))) : allThreads;
  const own = (message: Message) => message.authorId === profile.id;
  const submit = () => {
    if (!text.trim() || !live.canWrite || text.trim().length > 20000) return;
    try {
      const now = Date.now(); let next = live.replica.readThreads(); const content = text.trim();
      live.replica.doc.transact(() => {
        if (reply || editing) {
          const context = (editing ?? reply)!; const thread = next.find(thread => thread.id === context.threadId); const original = thread?.messages.find(message => message.id === context.message.id);
          if (!thread || !original || original.deleted) throw new Error("原消息已删除，草稿已保留");
          if (editing && (!own(original) || original.text !== editing.message.text)) throw new Error("这条消息已变化，请重新打开后修改");
          next = next.map(item => item.id !== thread.id ? item : { ...item, messages: editing ? item.messages.map(message => message.id === original.id ? { ...message, text: content, editedAt: now } : message) : [...item.messages, { id: uuid(), author: profile.displayName, authorId: profile.id, text: content, createdAt: now, replyTo: original.id, deleted: false }] });
        } else {
          const id = uuid(); const document = live.replica.readRoot(); const paragraph = target ? findNode(document, target.id) : null;
          if (target && !paragraph) throw new Error("原段落已删除，草稿已保留。可改为文档评论。");
          if (paragraph) { paragraph.attrs = { ...paragraph.attrs, writemeCommentIds: [...(paragraph.attrs?.writemeCommentIds ?? []) as string[], id] }; live.replica.writeRoot(document); }
          next = [...next, { id, quote: target?.text.slice(0, 2000) ?? "", anchored: !!target, wholeBlock: !!target, messages: [{ id: uuid(), author: profile.displayName, authorId: profile.id, text: content, createdAt: now, deleted: false }] }];
        }
        live.replica.writeThreads(next);
      }, localOrigin);
      setText(""); drafts.current.delete(key); setError(""); setEditing(null); setReply(null); input.current?.focus();
    } catch (error) { setError((error as Error).message); }
  };
  const remove = () => {
    if (!confirm || !live.canWrite) return;
    const thread = live.replica.readThreads().find(thread => thread.id === confirm.thread.id); if (!thread) { setConfirm(null); return; }
    const message = thread.messages.find(message => message.id === confirm.message.id); if (!message || !own(message) && live.role !== "owner") return;
    if (message.id === thread.messages[0].id) live.replica.writeThreads(live.replica.readThreads().filter(item => item.id !== thread.id));
    else live.replica.writeThreads(live.replica.readThreads().map(item => item.id === thread.id ? { ...item, messages: item.messages.map(item => item.id === message.id ? { ...item, text: "", deleted: true, editedAt: null } : item) } : item));
    setConfirm(null);
  };
  return <aside className="shared-comments"><div className="shared-comments-heading"><div><BubbleIcon /><h3>{target ? "段落评论" : "全部评论"}</h3><span>{threads.length}</span></div><button className="shared-icon" aria-label="关闭评论" onClick={close}><Icon name="close" size={16} /></button></div>{target && <div className="shared-comment-context"><small>正在讨论这一段</small><p>{target.text || "空白段落"}</p><button onClick={all}>查看全部评论 →</button></div>}
    <div className="shared-comment-list">{!threads.length && <div className="shared-comment-empty"><BubbleIcon /><h4>交流，从这里开始</h4><p>把想法留在具体的段落旁，<br />也可以接着伙伴的消息回复。</p></div>}{threads.map(thread => <section key={thread.id} className="shared-thread" data-thread-id={thread.id}>{!target && thread.anchored && <blockquote>{thread.quote || "空白段落"}</blockquote>}{thread.messages.map((message, i) => {
      const parent = thread.messages.find(parent => parent.id === message.replyTo);
      return <div key={message.id} className={`shared-message ${i ? "reply" : ""}`} data-message-id={message.id}><UserAvatar name={message.author} /><div className="shared-message-content"><div className="shared-byline"><b>{message.author}</b><time>{new Date(message.createdAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</time></div>{parent && <div className="shared-reply-context">回复 {parent.author}：{parent.deleted ? "这条回复已删除" : parent.text.slice(0, 70)}</div>}<p className={message.deleted ? "shared-muted" : ""}>{message.deleted ? "这条回复已删除" : message.text}</p>{message.editedAt && <small className="shared-muted">已编辑</small>}{!message.deleted && live.canWrite && <div className="shared-message-actions"><button onClick={() => { setReply({ threadId: thread.id, message }); setEditing(null); setTimeout(() => input.current?.focus(), 0); }}>回复</button>{own(message) && <button onClick={() => { setEditing({ threadId: thread.id, message }); setReply(null); setTimeout(() => input.current?.focus(), 0); }}>编辑</button>}{(own(message) || live.role === "owner") && <button onClick={() => setConfirm({ thread, message })}>删除</button>}</div>}</div></div>;
    })}{confirm?.thread.id === thread.id && <div className="shared-comment-confirm"><p>{confirm.message.id === thread.messages[0].id ? "删除此讨论及全部回复？" : "删除这条回复？后续回复会保留。"}</p><button className="shared-danger" onClick={remove}>确认删除</button><button className="shared-link" onClick={() => setConfirm(null)}>取消</button></div>}</section>)}</div>
    <form className="shared-comment-composer" onSubmit={event => { event.preventDefault(); submit(); }}>{(reply || editing) && <div className="shared-composer-target"><span>{editing ? "编辑自己的消息" : `回复 ${reply?.message.author}`}</span><button type="button" aria-label="取消回复或编辑" onClick={() => { setReply(null); setEditing(null); }}><Icon name="close" size={13} /></button></div>}<textarea ref={input} aria-label="评论内容" placeholder={live.canWrite ? target ? "写下对这一段的想法…" : "留下一条评论…" : "你拥有此文档的阅读权限"} value={text} maxLength={20000} readOnly={!live.canWrite} onChange={event => setText(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && event.ctrlKey && !event.nativeEvent.isComposing) { event.preventDefault(); submit(); } }} /><div className="shared-composer-footer"><small>Ctrl + Enter 发送</small><button className="shared-primary" disabled={!text.trim() || !live.canWrite}>{editing ? "保存" : "发送"} ↑</button></div>{error && <p className="shared-error" role="alert">{error}</p>}</form></aside>;
}
function downloadDraft(live: LiveDocument) { const url = URL.createObjectURL(new Blob([JSON.stringify(live.replica.readRoot(), null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = `${displayTitle(live.replica.title.toString())}-草稿.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function PeopleIcon() { return <svg width="18" height="18" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.4"><circle cx="8" cy="6" r="3" /><path d="M2 17v-2c0-5 12-5 12 0v2M13 3a3 3 0 0 1 0 6M15 11c3 0 3 3 3 6" /></svg>; }
